.PHONY: build test cross-build

build:
	go build -o bin/seamless-cors ./cmd/seamless-cors

test:
	go test ./...

cross-build:
	GOOS=darwin GOARCH=amd64 go build ./...
	GOOS=darwin GOARCH=arm64 go build ./...
	GOOS=windows GOARCH=amd64 go build ./...
	GOOS=windows GOARCH=arm64 go build ./...
